{
 "title": "Aptos Validator Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": "validator-0,fullnode-0" },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Node liveness - Node appears here if down",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_current_round{role=\"validator\"}[1m]) == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Node Version",
   "type": "stat",
   "description": "Version reported by nodes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{instance=~\"${instance}\",type=\"synced\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Epoch",
   "type": "stat",
   "description": "Epoch reported by nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{instance=~\"${instance}\",type=\"synced_epoch\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Status",
   "type": "stat",
   "description": "Consensus Data reported by nodes",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_epoch{instance=~\"${instance}\"}",
     "legendFormat": "Consensus Epoch"
    },
    {
     "expr": "aptos_consensus_current_round{instance=~\"${instance}\"}",
     "legendFormat": "Consensus Round"
    }
   ]
  },
  {
   "title": "Vals in Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_current_epoch_validators{instance=~\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Total Txns Since Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}"
    }
   ]
  },
  {
   "title": "Current Txn Rate",
   "type": "stat",
   "description": "Transactions per second (5m average)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=~\"success\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed/Retried Txn %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=~\"retry|failed\"}) / sum(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Rate",
   "type": "stat",
   "description": "Proposals per minute over the last 5 minutes",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_proposals_count{instance=~\"${instance}\"}[15m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposals Sent",
   "type": "stat",
   "description": "Proposals sent by validator",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aptos_consensus_proposals_count{instance=~\"${instance}\"}[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "increase(aptos_consensus_proposals_count{instance=~\"${instance}\"}[1h])",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "increase(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[6h])",
     "legendFormat": "Last 6h"
    },
    {
     "expr": "increase(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[24h])",
     "legendFormat": "Last 1d"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "stat",
   "description": "Failures per minute over the last 5 minutes",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aptos_failed_proposals_in_window{instance=~\"${instance}\"}[5m])",
     "legendFormat": "Last 5m"
    }
   ]
  },
  {
   "title": "Failed Proposals",
   "type": "stat",
   "description": "Failed proposals in window from validator over period",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{instance=~\"${instance}\"}[1h]))",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{instance=~\"${instance}\"}[6h]))",
     "legendFormat": "Last 6h"
    },
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[12h]))",
     "legendFormat": "Last 12h"
    },
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[24h]))",
     "legendFormat": "Last 1d"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "stat",
   "description": "Peer connections",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aptos_connections{instance=\"validator-0\",role_type=\"validator\",network_id=\"Validator\",network_id!=\"vfn\"})",
     "legendFormat": "Val Connections"
    },
    {
     "expr": "sum(aptos_connections{instance=\"fullnode-0\",role_type=\"full_node\",network_id!=\"vfn\"})",
     "legendFormat": "VFN Connections"
    }
   ]
  },
  {
   "title": "VFN Connected?",
   "type": "stat",
   "description": "Captures if the full node is connected.  Network ID in config file must be `vfn`.",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aptos_connections{instance=\"fullnode-0\",network_id=\"vfn\",role_type=\"validator\"})",
     "legendFormat": "Inbound - {{instance}}"
    }
   ]
  },
  {
   "title": "DB Success %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(aptos_storage_api_latency_seconds_count{instance=~\"${instance}\",result=\"Ok\"}[1m])) / sum by (instance) (irate(aptos_storage_api_latency_seconds_count{instance=~\"${instance}\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Validator Connections (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_connections{instance=~\"validator-0\",direction=\"inbound\",role_type=\"validator\",network_id=\"Validator\"}",
     "legendFormat": "Inbound - {{instance}}"
    },
    {
     "expr": "aptos_connections{instance=~\"validator-0\",direction=\"outbound\",role_type=\"validator\",network_id=\"Validator\"}",
     "legendFormat": "Outbound - {{instance}}"
    }
   ]
  },
  {
   "title": "Full Node Connections (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_connections{instance=\"fullnode-0\",direction=\"inbound\",role_type=\"full_node\",network_id!=\"vfn\"}",
     "legendFormat": "Inbound - {{instance}}"
    },
    {
     "expr": "aptos_connections{instance=\"fullnode-0\",direction=\"outbound\",role_type=\"full_node\",network_id!=\"vfn\"}",
     "legendFormat": "Outbound - {{instance}}"
    }
   ]
  },
  {
   "title": "Proposals Sent By Validator / min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_proposals_count{instance=~\"${instance}\",instance=~\"${instance}.*\"}[15m]) * 60",
     "legendFormat": "Proposals /min - $instance"
    },
    {
     "expr": "rate(aptos_consensus_proposals_count{instance=~\"${instance}\",instance=~\"${instance}.*\"}[6h]) * 60",
     "legendFormat": "Proposals /min - 6hr avg"
    },
    {
     "expr": "rate(aptos_consensus_proposals_count{instance=~\"${instance}\"}[1d]) * 60",
     "legendFormat": "Proposals /min - 24hr avg"
    },
    {
     "expr": "(increase(aptos_consensus_proposals_count{instance=~\"${instance}\"}[45s]))",
     "legendFormat": "Proposal Sent"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 / rate(aptos_consensus_committed_blocks_count{instance=~\"${instance}\"}[5m])",
     "legendFormat": "Block Time - {{instance}}"
    },
    {
     "expr": "1 / rate(aptos_consensus_committed_blocks_count{instance=~\"${instance}\"}[6h])",
     "legendFormat": "Block Time - 6hr avg"
    },
    {
     "expr": "1 / rate(aptos_consensus_committed_blocks_count{instance=~\"${instance}\"}[24h])",
     "legendFormat": "Block Time - 24hr avg"
    }
   ]
  },
  {
   "title": "Committed and Failed Proposals in Window",
   "type": "timeseries",
   "description": "Failed proposals in window for this validator",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(aptos_committed_proposals_in_window{instance=~\"${instance}\"})",
     "legendFormat": "Committed - $instance"
    },
    {
     "expr": "(aptos_failed_proposals_in_window{instance=~\"${instance}\"})",
     "legendFormat": "Failures - $instance"
    },
    {
     "expr": "aptos_consensus_current_round{instance=~\"${instance}\"}",
     "legendFormat": "Round"
    }
   ]
  },
  {
   "title": "Schema get() Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(aptos_schemadb_get_latency_seconds_sum{instance=~\"${instance}\"}[1m])) / sum by (instance) (irate(aptos_schemadb_get_latency_seconds_count{instance=~\"${instance}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Rounds /sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_current_round{instance=~\"${instance}\"}[1m])",
     "legendFormat": "Rounds /sec"
    }
   ]
  },
  {
   "title": "Transactions /sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}[5m])",
     "legendFormat": "Transactions /sec {{instance}}"
    },
    {
     "expr": "rate(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}[6h])",
     "legendFormat": "Transactions /sec - 6hr avg"
    },
    {
     "expr": "rate(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}[1d])",
     "legendFormat": "Transactions /sec - 24hr avg"
    }
   ]
  },
  {
   "title": "Txn Totals",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "increase(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}[1h])",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "increase(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}[6h])",
     "legendFormat": "Last 6h"
    },
    {
     "expr": "increase(aptos_consensus_committed_txns_count{instance=~\"${instance}\",state=\"success\"}[1d])",
     "legendFormat": "Last 1d"
    }
   ]
  },
  {
   "title": "mempool index size",
   "type": "timeseries",
   "description": "Size of a core mempool index",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{instance=~\"${instance}\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Block Commit Time Distribution (s)",
   "type": "bargauge",
   "description": "The total time spent in seconds of commiting blocks in Aptos executor ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_executor_commit_blocks_seconds_bucket{instance=~\"${instance}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block Execute Time Distribution (s)",
   "type": "bargauge",
   "description": "The total time spent in seconds of block execution in the block executor.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_executor_execute_block_seconds_bucket{instance=~\"${instance}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}